### ISSUE TITLE
ClassNotFoundException javassist

### ISSUE THREAD

**Issue by Rostom35** [amullier/M2INFO-VV-PROJET#8]
When we make mutation in a method, we would like to load the mutated class so then launch the tests, so we call toClass() method of CtClass to have a class object of the mutated class, but we get an exception (ClassNotFoundException).

## Solution 
write the mutate class in target directory, and then the TestRunner have to seach on it.

###  What we are doing: 
```
Mutator ( generate mutant ) ---> load the mutated class object ----> give the mutated class object to TestRunner ----> TestRunner run test's project including the mutated class. 
[ We have ClassNotFoundException when we load the mutated class object ]
```
### Possible solution : 
```
Mutator ( generate mutant ) ---> write the mutated class in target directory ---->TestRunner have to load the class by searching in target directory ----> TestRunner run test's project including the mutated class. 
```

A tester ....

**Comment by amullier** [comment]
Seems to be a good idea, Mutator work is only focus on Mutated class generation not loading.
BUT, we have to separate loading classes from testrunner in a dedicated component.
